kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo
spec:
  template:
    metadata:
      labels:
        name: demo
    spec:
      containers:
        - image: lowet84/k8s-workshop
          name: demo
          volumeMounts:
            - mountPath: /host
              name: hostname
          env:
            - name: name
              value: 'Fredrik'
      volumes:
        - name: hostname
          hostPath:
            path: /etc/hostname
