version: '3.4'
services:
  k8s-demo-server:
    container_name: k8s-demo-server
    image: demo-server
    build: .
    labels:
      - traefik.ws.port=8080
      - traefik.ws.frontend.rule=Host:k8sws.fredriklowenhamn.se
      - traefik.web.port=8081
      - traefik.web.frontend.rule=Host:k8sdemo.fredriklowenhamn.se
      - traefik.enable=true
    networks:
      - core

networks:
  core:
    external: true
